...

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -3,11 +3,11 @@ name: Build
 on:
   push:
     branches:
-      - "master"
+      - 'master'
     paths-ignore:
-      - "*.md"
-      - "*.sh"
-      - "release.yaml"
+      - '*.md'
+      - '*.sh'
+      - 'release.yaml'
   #      - "sync_frp.yaml"
 
   workflow_dispatch:
@@ -16,7 +16,7 @@ jobs:
   android:
     runs-on: ubuntu-latest
     env:
-      output: "${{ github.workspace }}/build/app/outputs/apk/release"
+      output: '${{ github.workspace }}/build/app/outputs/apk/release'
     steps:
       - uses: actions/checkout@v3
         with:
@@ -59,8 +59,8 @@ jobs:
       - name: Upload AAR
         uses: actions/upload-artifact@v3
         with:
-          name: "AList"
-          path: "${{ github.workspace }}/android/app/libs/*.aar"
+          name: 'AList'
+          path: '${{ github.workspace }}/android/app/libs/*.aar'
 
       - name: Init Signature
         run: |
@@ -82,8 +82,8 @@ jobs:
         if: failure() && steps.gradle.outcome != 'success'
         uses: actions/upload-artifact@v3
         with:
-          name: "missing_rules"
-          path: "${{ github.workspace }}/build/app/outputs/mapping/release/missing_rules.txt"
+          name: 'missing_rules'
+          path: '${{ github.workspace }}/build/app/outputs/mapping/release/missing_rules.txt'
 
       - name: Init APP Version Name
         run: |
@@ -93,19 +93,19 @@ jobs:
         if: success () || failure ()
         uses: actions/upload-artifact@v3
         with:
-          name: "AListFlutter-v${{ env.ver_name }}_arm64-v8a"
-          path: "${{ env.output }}/*-v8a.apk"
+          name: 'AListFlutter-v${{ env.ver_name }}_arm64-v8a'
+          path: '${{ env.output }}/*-v8a.apk'
 
-      - name: Upload App To Artifact arm-v7a
-        if: success () || failure ()
-        uses: actions/upload-artifact@v3
-        with:
-          name: "AListFlutter-v${{ env.ver_name }}_arm-v7a"
-          path: "${{ env.output }}/*-v7a.apk"
+      # - name: Upload App To Artifact arm-v7a
+      #   if: success () || failure ()
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: "AListFlutter-v${{ env.ver_name }}_arm-v7a"
+      #     path: "${{ env.output }}/*-v7a.apk"
 
-      - name: Upload App To Artifact x86
-        if: success () || failure ()
-        uses: actions/upload-artifact@v3
-        with:
-          name: "AListFlutter-v${{ env.ver_name }}_x86_64"
-          path: "${{ env.output }}/*64.apk"
+      # - name: Upload App To Artifact x86
+      #   if: success () || failure ()
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: "AListFlutter-v${{ env.ver_name }}_x86_64"
+      #     path: "${{ env.output }}/*64.apk"
